### ISSUE TITLE
SSH Connection Failed

### ISSUE THREAD

**Issue by EmnaX** [blinksh/blinksh.github.io#2]
I have an Ubuntu 16.04 server which is a bit slow when connecting over SSH. It's an i5 but for whatever reason, the SSH connection takes longer than normal to establish. I have never had an issue connecting to it using Kitty on Windows, the terminal on MacOS or Prompt 2 on iOS. For whatever reason, I can't get Blink Shell on iOS to connect with this server. It seems to time out very quickly though and give me the error:
    Connected to 10.10.10.13
    Could not connect to host: Error establishing SSH session.

Is there anyway to increase the time Blink Shell will wait to establish the connection? Are there more detailed logs stored in the Blink Shell app somewhere that I can access?

**Comment by carloscabanero** [comment]
Hi again! You can run it in verbose mode, (-v on ssh, --verbose on mosh). Usually Blink has around 30 seconds timeout, so that shouldn't be what is going on. There might be something going on during the handshake, or maybe an authentication method that we do not support. If you can copy paste the error here I might be able to give you more instructions.

**Comment by EmnaX** [comment]
Hi Carlso,

Thanks for the info! Re-running the ssh command from my phone produces the following output:

blink> ssh -v ubuntu
SSHSession:DEBUG:Connecting to ubuntu.matigue.com [10.10.10.13] port 22.
Connected to 10.10.10.13
SSHSession:DEBUG:Unable to exchange encryption keys
Could not connect to host: Error establishing SSH session.
blink>

The error doesn't say the key is bad or anything but rather, it is unable to exchange the encryption keys. I am using the same key to log onto other servers just fine.

Googling around a bit, it looks like this may be related to libssh2?

**Comment by EmnaX** [comment]
I was playing around with this some more and here are the two log entries from /var/log/auth.log on the Ubuntu server I am trying to connect too:

[Connection attempt from Blink Shell]
Mar 23 15:59:57 ubuntu sshd[25194]: fatal: Unable to negotiate with 10.10.9.2 port 59994: no matching host key type found. Their offer: ssh-rsa,ssh-dss [preauth]                                               

[Connection attempt using Prompt 2]
Mar 23 16:00:23 ubuntu sshd[25203]: Accepted publickey for emnax from 10.10.9.2 port 59998 ssh2: RSA SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Both programs are using the same key. I do have the public key in the authorized_keys file for my user.

**Comment by carloscabanero** [comment]
This is definitely libssh2. Prompt2 supports ECDSA and maybe that's why they are able to pass the "host keys exchange" phase. Can you check if your server has is offering an rsa host key for exchange? I added another "feature" that I'm not publicising as it is insecure, which is to completely skip the host key exchange phase (-h). Would you mind trying that too?

We are currently in the process of evaluating whether we can move to libssh or another ssh library. The license would permit it given that we are GPLv3 too, and it would make a huge difference.

**Comment by EmnaX** [comment]
That's what it was Carlos!

/etc/ssh/sshd_config had the line "HostKey /etc/ssh/ssh_host_rsa_key" commented out. I put it back in, restarted sshd and connecting via Blink Shell works perfectly now!

I guess now would be a good time to put in a feature request for ED25519 key support :)

Thanks for all your help on this, I would have been banging my head for a while trying to figure it out.

**Comment by carloscabanero** [comment]
Glad you made it work! ED25519 and a few others are the reason why we wanna move away from libssh2. We are making changes to the backend and see how far we can go!

Thanks for your message and support! ;)
